version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    links:
      - postgres
  postgres:
    image: postgres:14.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
