version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    links:
      - postgres
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  postgres:
    image: postgres:14.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./postgres/init-database.sql:/docker-entrypoint-initdb.d/init-database.sql:ro
volumes:
  db:
    driver: local
